<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class SchoolCampusesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('school_campuses')->delete();
        
        \DB::table('school_campuses')->insert(array (
            0 => 
            array (
                'id' => 1,
                'oldname' => 'ANDRES BONIFACIO COLLEGE',
                'campus' => 'DIPOLOG',
                'address' => 'MIPUTAK',
                'is_main' => 1,
                'is_active' => 1,
                'school_id' => 1,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '097202000',
                'province_code' => '097200000',
                'region_code' => '090000000',
                'assigned_region' => '090000000',
                'created_at' => '2023-05-21 14:13:42',
                'updated_at' => '2023-05-21 14:13:42',
            ),
            1 => 
            array (
                'id' => 2,
                'oldname' => 'ATENEO DE ZAMBOANGA UNIVERSITY',
                'campus' => 'SALVADOR',
                'address' => 'LA PURISIMA ST.',
                'is_main' => 1,
                'is_active' => 1,
                'school_id' => 2,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '097332000',
                'province_code' => '097300000',
                'region_code' => '090000000',
                'assigned_region' => '090000000',
                'created_at' => '2023-05-21 14:22:17',
                'updated_at' => '2023-05-21 14:22:17',
            ),
            2 => 
            array (
                'id' => 3,
                'oldname' => 'BASILAN STATE COLLEGE-ISABELA CITY',
                'campus' => 'ISABELA',
                'address' => 'SUMAGDANG',
                'is_main' => 1,
                'is_active' => 1,
                'school_id' => 3,
                'term_id' => 4,
                'grading_id' => 8,
                'municipality_code' => '099701000',
                'province_code' => '150700000',
                'region_code' => '150000000',
                'assigned_region' => '090000000',
                'created_at' => '2023-05-21 15:29:37',
                'updated_at' => '2023-05-21 15:29:37',
            ),
            3 => 
            array (
                'id' => 4,
                'oldname' => 'DIPOLOG CITY INSTITUTE OF TECHNOLOGY',
                'campus' => 'DIPOLOG',
                'address' => 'DAPITAN ROAD',
                'is_main' => 1,
                'is_active' => 1,
                'school_id' => 4,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '097202000',
                'province_code' => '097200000',
                'region_code' => '090000000',
                'assigned_region' => '090000000',
                'created_at' => '2023-05-21 15:31:20',
                'updated_at' => '2023-05-21 15:31:20',
            ),
            4 => 
            array (
                'id' => 5,
                'oldname' => 'DIPOLOG MEDICAL CENTER COLLEGE FOUNDATION, INC.-DIPOLOG CITY',
                'campus' => 'DIPOLOG',
                'address' => 'FR. PATANGAN ROAD, STA. FILOMENA ST.',
                'is_main' => 1,
                'is_active' => 1,
                'school_id' => 5,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '097202000',
                'province_code' => '097200000',
                'region_code' => '090000000',
                'assigned_region' => '090000000',
                'created_at' => '2023-05-21 15:34:29',
                'updated_at' => '2023-05-21 15:34:29',
            ),
            5 => 
            array (
                'id' => 6,
                'oldname' => 'JH CERILLES STATE COLLEGE',
                'campus' => 'PAGADIAN',
                'address' => 'MATI',
                'is_main' => 1,
                'is_active' => 1,
                'school_id' => 6,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '097322000',
                'province_code' => '097300000',
                'region_code' => '090000000',
                'assigned_region' => '090000000',
                'created_at' => '2023-05-21 15:36:53',
                'updated_at' => '2023-05-21 15:36:53',
            ),
            6 => 
            array (
                'id' => 7,
                'oldname' => 'JOSE RIZAL MEMORIAL STATE UNIVERSITY-DAPITAN CITY',
                'campus' => 'DAPITAN',
                'address' => 'GUADING ADASA ST., STA. CRUZ',
                'is_main' => 1,
                'is_active' => 1,
                'school_id' => 7,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '097201000',
                'province_code' => '097200000',
                'region_code' => '090000000',
                'assigned_region' => '090000000',
                'created_at' => '2023-05-21 15:53:19',
                'updated_at' => '2023-05-21 15:53:19',
            ),
            7 => 
            array (
                'id' => 8,
                'oldname' => 'JOSE RIZAL MEMORIAL STATE UNIVERSITY-KATIPUNAN',
                'campus' => 'KATIPUNAN',
                'address' => 'REGIONAL HIGHWAY DIPOLOG-SINDANGAN',
                'is_main' => 0,
                'is_active' => 1,
                'school_id' => 7,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '097203000',
                'province_code' => '097200000',
                'region_code' => '090000000',
                'assigned_region' => '090000000',
                'created_at' => '2023-05-21 15:54:12',
                'updated_at' => '2023-05-21 15:54:12',
            ),
            8 => 
            array (
                'id' => 9,
                'oldname' => 'JOSE RIZAL MEMORIAL STATE UNIVERSITY-TAMPILISAN',
                'campus' => 'TAMPILISAN',
                'address' => 'ZNAC ROAD',
                'is_main' => 0,
                'is_active' => 1,
                'school_id' => 7,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '097221000',
                'province_code' => '097200000',
                'region_code' => '090000000',
                'assigned_region' => '090000000',
                'created_at' => '2023-05-21 15:55:12',
                'updated_at' => '2023-05-21 15:55:12',
            ),
            9 => 
            array (
                'id' => 10,
                'oldname' => 'JOSE RIZAL MEMORIAL STATE UNIVERSITY',
                'campus' => 'DIPOLOG',
                'address' => 'GENERAL LUNA ST.',
                'is_main' => 0,
                'is_active' => 1,
                'school_id' => 7,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '097202000',
                'province_code' => '097200000',
                'region_code' => '090000000',
                'assigned_region' => '090000000',
                'created_at' => '2023-05-21 15:56:00',
                'updated_at' => '2023-05-21 15:56:00',
            ),
            10 => 
            array (
                'id' => 11,
                'oldname' => 'MEDINA COLLEGE-PAGADIAN',
                'campus' => 'PAGADIAN',
                'address' => 'BULATOK DISTRICT',
                'is_main' => 1,
                'is_active' => 1,
                'school_id' => 8,
                'term_id' => 4,
                'grading_id' => 8,
                'municipality_code' => '097322000',
                'province_code' => '097300000',
                'region_code' => '090000000',
                'assigned_region' => '090000000',
                'created_at' => '2023-05-21 16:00:03',
                'updated_at' => '2023-05-21 16:00:03',
            ),
            11 => 
            array (
                'id' => 12,
                'oldname' => 'MINDANAO STATE UNIVERSITY MARAWI EXTENSION-SINDANGAN',
                'campus' => 'MAIN CAMPUS SINDANGAN EXT.',
                'address' => 'BALOK',
                'is_main' => 0,
                'is_active' => 1,
                'school_id' => 9,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '097218000',
                'province_code' => '097200000',
                'region_code' => '090000000',
                'assigned_region' => '090000000',
                'created_at' => '2023-05-21 16:18:50',
                'updated_at' => '2023-05-21 16:18:50',
            ),
            12 => 
            array (
                'id' => 13,
                'oldname' => 'MINDANAO STATE UNIVERSITY-BUUG',
                'campus' => 'BUUG',
                'address' => 'DATU PANAS ST.',
                'is_main' => 0,
                'is_active' => 1,
                'school_id' => 9,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '098302000',
                'province_code' => '098300000',
                'region_code' => '090000000',
                'assigned_region' => '090000000',
                'created_at' => '2023-05-21 16:19:59',
                'updated_at' => '2023-05-21 16:19:59',
            ),
            13 => 
            array (
                'id' => 14,
                'oldname' => 'SAINT COLUMBAN COLLEGE',
                'campus' => 'PAGADIAN',
                'address' => 'CORNER ALANO & SAGON ST., SAN FRANCISCO DISTRICT',
                'is_main' => 1,
                'is_active' => 1,
                'school_id' => 10,
                'term_id' => 4,
                'grading_id' => 8,
                'municipality_code' => '097322000',
                'province_code' => '097300000',
                'region_code' => '090000000',
                'assigned_region' => '090000000',
                'created_at' => '2023-05-21 16:22:05',
                'updated_at' => '2023-05-21 16:22:05',
            ),
            14 => 
            array (
                'id' => 15,
                'oldname' => 'SAINT JOSEPH COLLEGE OF SINDANGAN',
                'campus' => 'SINDANGAN',
                'address' => 'JOSE BURGOS ST. NATIONAL HIGHWAY',
                'is_main' => 1,
                'is_active' => 1,
                'school_id' => 11,
                'term_id' => 4,
                'grading_id' => 8,
                'municipality_code' => '097218000',
                'province_code' => '097200000',
                'region_code' => '090000000',
                'assigned_region' => '090000000',
                'created_at' => '2023-05-21 16:24:58',
                'updated_at' => '2023-05-21 16:24:58',
            ),
            15 => 
            array (
                'id' => 16,
                'oldname' => 'SOUTHERN MINDANAO COLLEGES-PAGADIAN CITY',
                'campus' => 'PAGADIAN',
                'address' => 'JAMISOLA ST, STA.LUCIA',
                'is_main' => 1,
                'is_active' => 1,
                'school_id' => 13,
                'term_id' => 4,
                'grading_id' => 8,
                'municipality_code' => '097322000',
                'province_code' => '097300000',
                'region_code' => '090000000',
                'assigned_region' => '090000000',
                'created_at' => '2023-05-21 16:31:16',
                'updated_at' => '2023-05-21 16:31:16',
            ),
            16 => 
            array (
                'id' => 17,
                'oldname' => 'ZAMBOANGA A.E. COLLEGE',
                'campus' => 'ZAMBOANGA',
                'address' => 'EUSTAQUIO QUADRANGLE, J.S. ALANO ST. ZONE III',
                'is_main' => 1,
                'is_active' => 1,
                'school_id' => 14,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '097332000',
                'province_code' => '097300000',
                'region_code' => '090000000',
                'assigned_region' => '090000000',
                'created_at' => '2023-05-21 16:32:51',
                'updated_at' => '2023-05-21 16:32:51',
            ),
            17 => 
            array (
                'id' => 18,
                'oldname' => 'WESTERN MINDANAO STATE UNIVERSITY-ZAMBOANGA CITY',
                'campus' => 'ZAMBOANGA',
                'address' => 'NORMAL ROAD, BALIWASAN',
                'is_main' => 1,
                'is_active' => 1,
                'school_id' => 15,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '097332000',
                'province_code' => '097300000',
                'region_code' => '090000000',
                'assigned_region' => '090000000',
                'created_at' => '2023-05-21 16:34:07',
                'updated_at' => '2023-05-21 16:34:07',
            ),
            18 => 
            array (
                'id' => 19,
                'oldname' => 'WESTERN MINDANAO STATE UNIVERSITY-IPIL',
                'campus' => 'IPIL',
                'address' => 'IPIL HEIGHTS',
                'is_main' => 0,
                'is_active' => 1,
                'school_id' => 15,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '098305000',
                'province_code' => '098300000',
                'region_code' => '090000000',
                'assigned_region' => '090000000',
                'created_at' => '2023-05-21 16:34:50',
                'updated_at' => '2023-05-21 16:34:50',
            ),
            19 => 
            array (
                'id' => 20,
                'oldname' => 'ZAMBOANGA CITY STATE POLYTECHNIC COLLEGE',
                'campus' => 'ZAMBOANGA',
                'address' => 'R.T. LIM, BOULEVARD, BALIWASAN',
                'is_main' => 1,
                'is_active' => 1,
                'school_id' => 16,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '097332000',
                'province_code' => '097300000',
                'region_code' => '090000000',
                'assigned_region' => '090000000',
                'created_at' => '2023-05-21 16:37:42',
                'updated_at' => '2023-05-21 16:37:42',
            ),
            20 => 
            array (
                'id' => 21,
                'oldname' => 'ZAMBOANGA STATE COLLEGE OF MARINE SCIENCE AND TECHNOLOGY',
                'campus' => 'ZAMBOANGA',
                'address' => 'RIO HONDO',
                'is_main' => 1,
                'is_active' => 1,
                'school_id' => 17,
                'term_id' => 4,
                'grading_id' => 9,
                'municipality_code' => '097332000',
                'province_code' => '097300000',
                'region_code' => '090000000',
                'assigned_region' => '090000000',
                'created_at' => '2023-05-21 16:41:07',
                'updated_at' => '2023-05-21 16:41:07',
            ),
            21 => 
            array (
                'id' => 22,
                'oldname' => 'SAINT VINCENT`S COLLEGE-DIPOLOG CITY',
                'campus' => 'DIPOLOG',
                'address' => 'PADRE RAMON ST., ESTAKA',
                'is_main' => 1,
                'is_active' => 1,
                'school_id' => 12,
                'term_id' => 4,
                'grading_id' => 8,
                'municipality_code' => '097202000',
                'province_code' => '097200000',
                'region_code' => '090000000',
                'assigned_region' => '090000000',
                'created_at' => '2023-05-22 02:12:31',
                'updated_at' => '2023-05-22 02:12:31',
            ),
        ));
        
        
    }
}